import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent } from "./ui/card";
import { ArrowDown, ArrowUp, Droplets, Wind } from "lucide-react";
const CurrentWeather = ({ data, locationName }) => {
    const { weather: [CurrentWeather], main: { temp, feels_like, temp_min, temp_max, humidity }, wind: { speed }, } = data;
    const formatTemp = (temp) => `${Math.round(temp)}°`;
    return (_jsx(Card, { className: "overflow-hidden rounded-xl shadow-sm", children: _jsx(CardContent, { className: "p-6", children: _jsxs("div", { className: "grid gap-6 md:grid-cols-2", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex items-end gap-1", children: [_jsx("h2", { className: "text-2xl font-bold tracking-tighter", children: locationName?.name }), locationName?.state && (_jsxs("span", { className: "text-muted-foreground", children: [", ", locationName.state] }))] }), _jsx("p", { className: "text-sm text-muted-foreground", children: locationName?.country })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("p", { className: "text-7xl font-bold tracking-tighter", children: formatTemp(temp) }), _jsxs("div", { className: "space-y-1", children: [_jsxs("p", { className: "text-sm font-medium text-muted-foreground", children: ["Feels like ", formatTemp(feels_like)] }), _jsxs("div", { className: "flex gap-2 text-sm font-medium", children: [_jsxs("span", { className: "flex items-center gap-1 text-blue-500", children: [_jsx(ArrowDown, { className: "h-3 w-3" }), formatTemp(temp_min)] }), _jsxs("span", { className: "flex items-center gap-1 text-red-500", children: [_jsx(ArrowUp, { className: "h-3 w-3" }), formatTemp(temp_max)] })] })] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Droplets, { className: "h-4 w-4 text-blue-500" }), _jsxs("div", { className: "space-y-0.5", children: [_jsx("p", { className: "text-sm font-medium", children: "Humidity" }), _jsxs("p", { className: "text-sm text-muted-foreground", children: [humidity, "%"] })] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Wind, { className: "h-4 w-4 text-blue-500" }), _jsxs("div", { className: "space-y-0.5", children: [_jsx("p", { className: "text-sm font-medium", children: "Wind Speed" }), _jsxs("p", { className: "text-sm text-muted-foreground", children: [speed, " m/s"] })] })] })] })] }), _jsx("div", { className: "flex flex-col items-center justify-center", children: _jsxs("div", { className: "relative flex aspect-square w-full max-w-[200px] items-center justify-center", children: [_jsx("img", { src: `https://openweathermap.org/img/wn/${CurrentWeather.icon}@4x.png`, alt: `Weather: ${CurrentWeather.description}`, className: "h-full w-full object-contain" }), _jsx("div", { className: "absolute bottom-0 text-center", children: _jsx("p", { className: "text-sm font-medium capitalize", children: CurrentWeather.description }) })] }) })] }) }) }));
};
export default CurrentWeather;
